# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  #- name: Home
   # url: '/'
    #weight: 5
  - name: Research
    url: '/'
    weight: 10
  - name: Opportunities
    url: '/opportunity'
    weight: 40
  - name: Publications
    url: '/publication'
    weight: 50
  - name: Team
    url: '/team'
    weight: 60
  - name: Photos
    url: '/photos'
    weight: 70
  - name: Contact
    url: '/contact'
    weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
